name: E2E Tests

on:
  push:
  workflow_dispatch:

  
jobs:
  run-cypress-tests:
    runs-on: [ubuntu-latest]
    container: cypress/included:13.13.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6.7.1

      - name: Archive Test Report (If Fails)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            ./cypress/screenshots/
            ./cypress/videos/
          retention-days: 7
